### PR TITLE
Add dinamic icon for color scheme preference

### PR DESCRIPTION
**Pull request by MonkiG**
I added a way to automatically change the icon when the user is using either dark mode or light mode. The reason is that when you are in the app with the dark mode activated, the icon has no contrast with the background and is difficult to visualize.

Before:
- On the app: 
  image
  
- Out the app:
  image

Now:
- On the app dark mode:
  image
- Out the app dark mode: 
  image

- On the app light mode:
  image
- Out the app light mode: 
  image

The icons are dynamically changed based on the user's preference. The custom hook receives the URLs for both the light and dark mode icons, allowing for flexibility and customization.

### CODE REVIEW

**Comment by afordigital** [comment]
WOW THIS IS BRUTAL!!! Thanks for this contribution!

**Comment by afordigital** [comment]
I need the PR to not have conflicts for approval

**Comment by MonkiG** [comment]
I already fixed the conflicts 😄

**Comment by juanpablo-is** [comment]
This functionality can be moved out of React and converted from a hook to a normal function, there is a flash where it initially loads the default icon and then determines the icon according to the match, this because it depends on the execution of React

Also, since it doesn't need React directly, you can remove the useEffect and let main.tsx execute the function

image

**Comment by MonkiG** [comment]
@juanpablo-is  You are right, this shouldn't be a hook since i'm using react unnecesary, but the icon flash will always happen because the plain html use the "default icon" in the link href and then js changes it given the preference, I don't think that there is a way to fix this little flash of the icon.

**Pull request merged**
